### ISSUE TITLE
Splash screen not shown on startup

### ISSUE THREAD

**Issue by TheOnAndOnlyZenomat** [rougier/emacs-splash#1]
I downloaded the splash-screen.el file and loaded it like recommended in the README, but it wont load on startup. The startupscreen is not inhibited, but when I activate the package, by ```require 'splash-screen``` in my init.el , it sends me to the scratch buffer instead of the custom splash screen.

When I activate it manually by ```M-x splash-screen``` it works.

**Comment by rougier** [comment]
Can you try `Emacs -Q -l nano-splash.el` and check if the screen is diplayed?

**Comment by TheOnAndOnlyZenomat** [comment]
If you mean ```emacs -Q -l splash-screen.el```, like loading the file directly, than that does not work. If you mean nano-splash.el specifically, than I dont have that file. It cant be found

**Comment by rougier** [comment]
I'm confused now... What README are you talking about exactly?

**Comment by TheOnAndOnlyZenomat** [comment]
The README for this repo, emacs-splash. Does this splashscreen belong to another package?

**Comment by rougier** [comment]
Oh sorry, I thought I was on another repository... Do you have any messages in the message buffer ?

**Comment by TheOnAndOnlyZenomat** [comment]
Happens^^ Already checked that, there were none

**Comment by rougier** [comment]
Can you try `M-x: splash-screen`?

I'm doing several tests to inhibit the splash-screen and  one of them may be wrong. If you're familiar (just a bit) with lisp, we can try to remove them one. by one to check which one fail. When you call splash-screen directly, the only relates to the number of "regular" buffer that must be 0. This is for inhibiting the splash screen if your start emacs with a file argument `(emacs myfile.txt`).

**Comment by TheOnAndOnlyZenomat** [comment]
I am not familiar with lisp, but if you are willing to, we still can try. I am positive, that I can pick up the stuff that I need for this.

When i try ```M-x: splash-screen``` it creates a buffer called ```splash``` but does not change to it and it displays nothing.

**Comment by rougier** [comment]
That's weird. Can you try to add `(insert "Hello")` just after [line 87](https://github.com/rougier/emacs-splash/blob/master/splash-screen.el#L87) and check if this is displayed ?

**Comment by TheOnAndOnlyZenomat** [comment]
I just noticed, that line 82 instead of a 0 there was a 1. Changing that to zero fixed it. I dont know how the 1 got there. Thanks for your help
